services:
  # create a SuperLink service
  superlink:
    image: flwr/superlink:1.10.0.dev20240717
    command:
      - --insecure

  # create a SuperNode service with two containers
  supernode-1:
    user: root
    build:
      context: .
      dockerfile_inline: |
        FROM flwr/supernode:1.10.0.dev20240717

        WORKDIR /app
        RUN python -m pip install -U --no-cache-dir \
            "flwr-datasets[vision]>=0.2.0,<1.0.0" \
            torch==2.2.1 \
            torchvision==0.17.1

        ENTRYPOINT ["flower-supernode", "client:app", "--node-config", "partition-id=0,num-partitions=2"]
    deploy:
      resources:
        limits:
          cpus: "2"
    command:
      - --superlink
      - superlink:9092
      - --insecure
    depends_on:
      - superlink
    volumes:
      - apps-volume:/app/.flwr/apps/:ro

  supernode-2:
    user: root
    build:
      context: .
      dockerfile_inline: |
        FROM flwr/supernode:1.10.0.dev20240717

        WORKDIR /app
        RUN python -m pip install -U --no-cache-dir \
            "flwr-datasets[vision]>=0.2.0,<1.0.0" \
            torch==2.2.1 \
            torchvision==0.17.1

        ENTRYPOINT ["flower-supernode", "client:app", "--node-config", "partition-id=1,num-partitions=2"]
    deploy:
      resources:
        limits:
          cpus: "2"
    command:
      - --superlink
      - superlink:9092
      - --insecure
    depends_on:
      - superlink
    volumes:
      - apps-volume:/app/.flwr/apps/:ro

  # create a SuperExec service
  superexec:
    user: root
    build:
      context: .
      dockerfile_inline: |
        FROM flwr/supernode:1.10.0.dev20240717

        WORKDIR /app
        RUN python -m pip install -U --no-cache-dir \
            "flwr-datasets[vision]>=0.2.0,<1.0.0" \
            torch==2.2.1 \
            torchvision==0.17.1

        ENTRYPOINT ["flower-superexec"]
    ports:
      - 9093:9093
    command:
      - --executor
      - flwr.superexec.deployment:executor
      - --insecure
      - --executor-config
      - superlink=superlink:9091
    depends_on:
      - superlink
    volumes:
      - apps-volume:/app/.flwr/apps/:rw

volumes:
     apps-volume:
